### ISSUE TITLE
ENDPOINT: StudyForm.vue

### ISSUE THREAD

**Issue by 1103-Rowell-Brandon** [HCI-UnrSeniorCapstone/2024-2025_Senior_Project#18]
**Description**: Need an endpoint for saving a complete form to the db
**Type**: POST
**Field**: temp hardcoded userID, study name, study description, study type (within vs between), # expected participants, array of tasks (task name, task description, task directions, duration, array of measurement types), array of factors (factor name, factor description) 
**Reference**:  See StudyForm.vue in views directory

**Comment by Jarvis-Nicholas** [comment]
- Relay success message back to frontend
