### ISSUE TITLE
ENDPOINT: StudyPanel.vue

### ISSUE THREAD

**Issue by 1103-Rowell-Brandon** [HCI-UnrSeniorCapstone/2024-2025_Senior_Project#25]
**Description**: When the user selects a study from the study table, a right slideout panel opens with greater details than displayed in the table including ALL info related to the study AND summary details for the sessions table. We should avoid sending the session results here (jairo results) for performance and only send session metrics if the user opens a particular sessions similar to what we are doing here with study). This means in this endpoint or a different we have to have a way to send from the VUE to Flask which study info is needed based on what row is clicked in the Study Table. 

**TYPE**: GET

**Field**: All study info not returned in the UserSession.vue ENDPOINT such as task stuff, factor stuff, task directions, measurement types, within vs between. For session info,  Date Conducted (day & time stamp created when a session is saved to the db), Session Name, Status (this will be a bool reported when a session is saved indicating there were no issues with the session aka valid/invalid); more advanced so maybe just have a column for it for now and it'll always be true until jairo gets the functionality working), Comments

**References**: See Study Right Panel for visual example

**Comment by Jarvis-Nicholas** [comment]
This is called "load_study" in the endpoints
